version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: fashioncart-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fashioncart
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
